//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeWorkProjectEntities1 : DbContext
    {
        public HomeWorkProjectEntities1()
            : base("name=HomeWorkProjectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HwToStydyClassOnDate> HwToStydyClassOnDate { get; set; }
        public virtual DbSet<Profession> Profession { get; set; }
        public virtual DbSet<ReportToStudentOnDate> ReportToStudentOnDate { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudyClass> StudyClass { get; set; }
        public virtual DbSet<StudyGroup> StudyGroup { get; set; }
        public virtual DbSet<SudentInStudyGroup> SudentInStudyGroup { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
    }
}
