//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.ReportToStudentOnDate = new HashSet<ReportToStudentOnDate>();
            this.SudentInStudyGroup = new HashSet<SudentInStudyGroup>();
        }
    
        public int studentId { get; set; }
        public string studentTz { get; set; }
        public string studentFirstName { get; set; }
        public string studentLastName { get; set; }
        public string studentPel { get; set; }
        public string studentCity { get; set; }
        public string studentAddress { get; set; }
        public string studentParentName { get; set; }
        public string studentParentPel { get; set; }
        public string studentParentEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportToStudentOnDate> ReportToStudentOnDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SudentInStudyGroup> SudentInStudyGroup { get; set; }
    }
}
